# Generated by Django 3.2.4 on 2021-06-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Talk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talk',
            name='venue',
            field=models.CharField(default='Zoom', max_length=200),
        ),
    ]
